/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostId = IDL.Text;
export const Time = IDL.Int;
export const Data__4 = IDL.Record({
  'id' : PostId,
  'author' : UserId,
  'timestamp' : Time,
  'caption' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const ReelId = IDL.Text;
export const Data__3 = IDL.Record({
  'id' : ReelId,
  'title' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'link' : IDL.Opt(IDL.Text),
  'author' : UserId,
  'timestamp' : Time,
});
export const StoryId = IDL.Text;
export const Data__2 = IDL.Record({
  'id' : StoryId,
  'text' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'expiry' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const MessageId = IDL.Text;
export const Data__5 = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
});
export const Data__1 = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'recipient' : UserId,
  'sender' : UserId,
  'timestamp' : Time,
});
export const Notification = IDL.Record({
  'content' : IDL.Text,
  'sender' : UserId,
  'timestamp' : Time,
});
export const TrackId = IDL.Text;
export const Data = IDL.Record({
  'id' : TrackId,
  'title' : IDL.Text,
  'audio' : ExternalBlob,
  'author' : UserId,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatRoomMessage' : IDL.Func([UserId, IDL.Text], [], []),
  'addNotification' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUserFromNotificationsRoom' : IDL.Func([IDL.Text, UserId], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [Data__4], []),
  'createPrivateChatRoom' : IDL.Func([IDL.Text], [], []),
  'createReel' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [Data__3],
      [],
    ),
  'createStory' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [Data__2], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'deleteReel' : IDL.Func([ReelId], [], []),
  'deleteStory' : IDL.Func([StoryId], [], []),
  'enterNotificationsRoom' : IDL.Func([IDL.Text], [], []),
  'enterNotificationsRoomAdminMode' : IDL.Func([IDL.Text], [], []),
  'enterPrivateChatRoom' : IDL.Func([UserId, IDL.Text], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Data__2)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatRoomMessages' : IDL.Func([UserId], [IDL.Vec(Data__5)], ['query']),
  'getFameLevel' : IDL.Func([], [IDL.Nat], ['query']),
  'getMessage' : IDL.Func([MessageId], [IDL.Opt(Data__1)], ['query']),
  'getMessages' : IDL.Func([UserId], [IDL.Vec(Data__1)], ['query']),
  'getNotificationsRoomEntries' : IDL.Func(
      [],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPosts' : IDL.Func([], [IDL.Vec(Data__4)], ['query']),
  'getPrivacySetting' : IDL.Func([], [IDL.Text], ['query']),
  'getReels' : IDL.Func([], [IDL.Vec(Data__3)], ['query']),
  'getStory' : IDL.Func([StoryId], [IDL.Opt(Data__2)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTracks' : IDL.Func([UserId], [IDL.Vec(Data)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsernames' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Data__1], []),
  'unbanUserFromNotificationsRoom' : IDL.Func([IDL.Text, UserId], [], []),
  'uploadTrack' : IDL.Func([IDL.Text, ExternalBlob], [Data], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostId = IDL.Text;
  const Time = IDL.Int;
  const Data__4 = IDL.Record({
    'id' : PostId,
    'author' : UserId,
    'timestamp' : Time,
    'caption' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const ReelId = IDL.Text;
  const Data__3 = IDL.Record({
    'id' : ReelId,
    'title' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'link' : IDL.Opt(IDL.Text),
    'author' : UserId,
    'timestamp' : Time,
  });
  const StoryId = IDL.Text;
  const Data__2 = IDL.Record({
    'id' : StoryId,
    'text' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'expiry' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const MessageId = IDL.Text;
  const Data__5 = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
  });
  const Data__1 = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'recipient' : UserId,
    'sender' : UserId,
    'timestamp' : Time,
  });
  const Notification = IDL.Record({
    'content' : IDL.Text,
    'sender' : UserId,
    'timestamp' : Time,
  });
  const TrackId = IDL.Text;
  const Data = IDL.Record({
    'id' : TrackId,
    'title' : IDL.Text,
    'audio' : ExternalBlob,
    'author' : UserId,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatRoomMessage' : IDL.Func([UserId, IDL.Text], [], []),
    'addNotification' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUserFromNotificationsRoom' : IDL.Func([IDL.Text, UserId], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [Data__4], []),
    'createPrivateChatRoom' : IDL.Func([IDL.Text], [], []),
    'createReel' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [Data__3],
        [],
      ),
    'createStory' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [Data__2], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'deleteReel' : IDL.Func([ReelId], [], []),
    'deleteStory' : IDL.Func([StoryId], [], []),
    'enterNotificationsRoom' : IDL.Func([IDL.Text], [], []),
    'enterNotificationsRoomAdminMode' : IDL.Func([IDL.Text], [], []),
    'enterPrivateChatRoom' : IDL.Func([UserId, IDL.Text], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Data__2)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatRoomMessages' : IDL.Func([UserId], [IDL.Vec(Data__5)], ['query']),
    'getFameLevel' : IDL.Func([], [IDL.Nat], ['query']),
    'getMessage' : IDL.Func([MessageId], [IDL.Opt(Data__1)], ['query']),
    'getMessages' : IDL.Func([UserId], [IDL.Vec(Data__1)], ['query']),
    'getNotificationsRoomEntries' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPosts' : IDL.Func([], [IDL.Vec(Data__4)], ['query']),
    'getPrivacySetting' : IDL.Func([], [IDL.Text], ['query']),
    'getReels' : IDL.Func([], [IDL.Vec(Data__3)], ['query']),
    'getStory' : IDL.Func([StoryId], [IDL.Opt(Data__2)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTracks' : IDL.Func([UserId], [IDL.Vec(Data)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsernames' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Data__1], []),
    'unbanUserFromNotificationsRoom' : IDL.Func([IDL.Text, UserId], [], []),
    'uploadTrack' : IDL.Func([IDL.Text, ExternalBlob], [Data], []),
  });
};

export const init = ({ IDL }) => { return []; };